#!/usr/bin/env python3
"""Render docs/protocol-coverage.md from the three files that decide it.

  protocols/*.json                  - what Graphite can name
  protocols/battle_tested_evidence.json - what mainnet showed about each one
  scripts/out/inventory_census.json - what mainnet was actually running

Nothing in the generated page is typed by hand, which is the point: the
protocol table in the docs went stale twice before (README listed Drift and
Kamino as OfficialManifest while the manifests said BattleTested, and Raydium
AMM V4 the other way round). `tests/docs_match_the_registry.rs` re-runs the
comparison in CI.
"""
import json
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
PROTOCOLS = HERE.parent / "protocols"
CENSUS = HERE / "out" / "inventory_census.json"
OUT = ROOT / "docs" / "protocol-coverage.md"

VOTE = "Vote111111111111111111111111111111111111111"


def load_manifests():
    out = {}
    for f in sorted(PROTOCOLS.glob("*.json")):
        if f.name in ("verified_program_ids.json", "battle_tested_evidence.json"):
            continue
        m = json.loads(f.read_text(encoding="utf-8"))
        out[m["protocol"]["program_id"]] = (f.name, m)
    return out


def qualifies(rec, th):
    return bool(
        rec.get("identity", {}).get("executable")
        and rec.get("volume", {}).get("successful_transactions_counted", 0)
        >= th["min_successful_transactions"]
        and rec.get("decode", {}).get("instructions_observed", 0)
        >= th["min_decoded_instructions"]
        and (rec.get("decode", {}).get("decode_rate") or 0) >= th["min_decode_rate"]
    )


def coverage(census, covered):
    """Invocation- and transaction-level coverage for a given manifest set."""
    programs = census["programs"]
    inv_all = sum(p["successful_txs"] for p in programs)
    inv_cov = sum(p["successful_txs"] for p in programs if p["program_id"] in covered)
    inv_all_nv = sum(p["successful_txs"] for p in programs if p["program_id"] != VOTE)
    inv_cov_nv = sum(
        p["successful_txs"] for p in programs
        if p["program_id"] in covered and p["program_id"] != VOTE
    )
    tx_total = tx_full = tx_top = tx_total_nv = tx_full_nv = tx_top_nv = 0
    for combo in census.get("transaction_program_sets", []):
        n = combo["transactions"]
        allp = set(filter(None, combo["all"].split("|")))
        topp = set(filter(None, combo["top_level"].split("|")))
        tx_total += n
        if allp <= covered:
            tx_full += n
        if topp <= covered:
            tx_top += n
        if allp != {VOTE}:
            tx_total_nv += n
            if allp <= covered:
                tx_full_nv += n
            if topp <= covered:
                tx_top_nv += n
    pct = lambda a, b: (100.0 * a / b) if b else 0.0  # noqa: E731
    return {
        "invocations": pct(inv_cov, inv_all),
        "invocations_no_vote": pct(inv_cov_nv, inv_all_nv),
        "transactions_every_program": pct(tx_full, tx_total),
        "transactions_every_program_no_vote": pct(tx_full_nv, tx_total_nv),
        "transactions_top_level": pct(tx_top, tx_total),
        "transactions_top_level_no_vote": pct(tx_top_nv, tx_total_nv),
        "sampled_transactions": tx_total,
        "sampled_transactions_no_vote": tx_total_nv,
    }


def main():
    manifests = load_manifests()
    ev_path = PROTOCOLS / "battle_tested_evidence.json"
    ev = json.loads(ev_path.read_text(encoding="utf-8"))
    th = ev["thresholds"]
    records = {r["program_id"]: r for r in ev["programs"]}
    census = json.loads(CENSUS.read_text(encoding="utf-8")) if CENSUS.exists() else None

    rank = {}
    if census:
        for i, p in enumerate(census["programs"]):
            rank[p["program_id"]] = (i + 1, p["successful_txs"])

    total_ix = sum(len(m["instructions"]) for _, m in manifests.values())
    battle = sorted(
        pid for pid in manifests
        if pid in records and qualifies(records[pid], th)
        and manifests[pid][1]["trust_tier"] == "BattleTested"
    )

    lines = []
    lines.append("# Protocol coverage — what Graphite can name, and what the chain runs")
    lines.append("")
    lines.append("> Generated by `graphite-core/scripts/render_coverage.py` from the manifests,")
    lines.append("> `protocols/battle_tested_evidence.json` and `scripts/out/inventory_census.json`.")
    lines.append("> Do not edit by hand — `tests/docs_match_the_registry.rs` compares this page to")
    lines.append("> the loaded registry, and a hand edit fails CI.")
    lines.append("")
    lines.append(f"Rendered: {time.strftime('%Y-%m-%d', time.gmtime())}")
    lines.append("")
    lines.append("## In one line")
    lines.append("")
    lines.append(
        f"**{len(manifests)} protocol manifests / {total_ix} instructions**, of which "
        f"**{len(battle)} carry a BattleTested tier that a mainnet measurement supports**."
    )
    lines.append("")
    lines.append("## What BattleTested means here")
    lines.append("")
    lines.append(
        "A manifest may *write* any tier it likes; the loader lowers `BattleTested` to "
        "`OfficialManifest` unless `protocols/battle_tested_evidence.json` shows all three of:"
    )
    lines.append("")
    lines.append(f"1. the program account exists on mainnet and is **executable**;")
    lines.append(
        f"2. at least **{th['min_successful_transactions']:,} successful transactions** carry its "
        "address, counted over a window the record states (the signature index answers for the "
        "address, not for invocation — axis 3 is what establishes use) — the same number "
        "`semantic_graph_store::thresholds::BATTLE_TESTED_TX` demands of evidence the node earns "
        "at runtime;"
    )
    lines.append(
        f"3. of at least **{th['min_decoded_instructions']} instructions actually observed** on "
        f"chain, the manifest can name at least **{th['min_decode_rate']:.0%}** — a transaction "
        "count alone cannot show that the declared surface still matches the deployed one."
    )
    lines.append("")
    lines.append(
        "The measurements are read-only (`getAccountInfo`, `getSignaturesForAddress`, "
        "`getTransaction`) and reproducible with `scripts/battle_tested_census.py`."
    )
    lines.append("")

    if census:
        covered = set(manifests)
        cov = coverage(census, covered)
        lines.append("## Coverage of real mainnet traffic")
        lines.append("")
        lines.append(
            f"Sampled {census['blocks_returned']} finalized blocks "
            f"({census['successful_transactions']:,} successful transactions, "
            f"{len(census['programs'])} distinct programs) with "
            "`scripts/solana_inventory_census.py`."
        )
        lines.append("")
        lines.append("| Measure | All traffic | Excluding validator votes |")
        lines.append("|---|---:|---:|")
        lines.append(
            f"| Program invocations Graphite can name | {cov['invocations']:.1f}% | "
            f"{cov['invocations_no_vote']:.1f}% |"
        )
        if cov["sampled_transactions"]:
            lines.append(
                f"| Transactions whose top-level programs are all manifested | "
                f"{cov['transactions_top_level']:.1f}% | "
                f"{cov['transactions_top_level_no_vote']:.1f}% |"
            )
            lines.append(
                f"| Transactions whose programs are manifested including CPI targets | "
                f"{cov['transactions_every_program']:.1f}% | "
                f"{cov['transactions_every_program_no_vote']:.1f}% |"
            )
        lines.append("")
        lines.append(
            "Validator vote transactions are separated out because no agent ever signs one; "
            "including them moves the percentages without changing what an agent is protected "
            "for."
        )
        lines.append("")
        lines.append(
            "The figure that matters most is measured by a different instrument, because it is "
            "the engine's own answer rather than a count over a block: `tools/mainnet-sample` "
            "runs whole finalized blocks through the full pipeline. On 10,617 transactions from "
            "8 blocks on 2026-09-22, the share of NON-VOTE transactions whose primary program "
            "Graphite can name was **44.0%** (1,498 of 3,405); on the **same sample** against "
            "the 33-manifest registry Round 18 started from, it was **20.8%** (708 of 3,405)."
        )
        lines.append("")
        vers = census.get("transaction_versions", {})
        if vers:
            tot = sum(vers.values())
            parts = ", ".join(
                f"{k}: {100.0 * v / tot:.1f}%" for k, v in sorted(vers.items())
            )
            lines.append(f"Transaction versions in the same sample — {parts}.")
            lines.append("")

    lines.append("## Every manifest")
    lines.append("")
    lines.append("| Protocol | Program ID | Ix | Tier | Successful txs measured | Window | Observed ix | Named |")
    lines.append("|---|---|---:|---|---:|---:|---:|---:|")
    def sort_key(pid):
        _, m = manifests[pid]
        return (0 if pid in battle else 1, -len(m["instructions"]), m["protocol"]["name"].lower())
    for pid in sorted(manifests, key=sort_key):
        fname, m = manifests[pid]
        rec = records.get(pid)
        tier = "BattleTested" if pid in battle else (
            "OfficialManifest" if m["trust_tier"] == "BattleTested" else m["trust_tier"]
        )
        if rec:
            v, d = rec["volume"], rec["decode"]
            txs = f"{v['successful_transactions_counted']:,}"
            win = f"{v['window_seconds']:,}s" if v.get("window_seconds") is not None else "—"
            obs = f"{d['instructions_observed']:,}"
            named = f"{d['decode_rate']:.0%}" if d.get("decode_rate") is not None else "—"
        else:
            txs = win = obs = named = "not measured"
        lines.append(
            f"| {m['protocol']['name']} | `{pid}` | {len(m['instructions'])} | {tier} | "
            f"{txs} | {win} | {obs} | {named} |"
        )
    lines.append("")
    lines.append("## Where the instruction surfaces come from")
    lines.append("")
    lines.append(
        "Manifests onboarded in Round 18 were generated from each program's **own on-chain "
        "Anchor IDL** — the account at `create_with_seed(find_program_address([], program), "
        '"anchor:idl", program)`, owned by the program itself — so the instruction names, '
        "discriminators, account order, writability and signer-ness are the deployed program's "
        "own statement, not a third-party copy. Where the IDL states a PDA derivation it is "
        "carried across verbatim; where it does not, the account is left ungrounded rather than "
        "given a guessed seed formula, because a wrong formula flags legitimate transactions "
        "(the C26 failure mode). Generation is reproducible: "
        "`scripts/fetch_onchain_idls.py` then `scripts/onboard_from_inventory.py`."
    )
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}: {len(manifests)} manifests, {total_ix} instructions, {len(battle)} battle-tested")


if __name__ == "__main__":
    main()
